use char cast to avoid std::filename::u8string error in android (#31)
u8string causes error when building inside android tree:
```
external/opencl-kernel-profiler/src/opencl-kernel-profiler.cpp:104:9: error: no matching conversion for functional-style cast from 'std::u8string' (aka 'basic_string<char8_t>') to 'perfetto::DynamicString'
  104 |         perfetto::DynamicString(filename.filename().generic_u8string()));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```